version: '3.7'
services:

  kratos-migrate:
    image: oryd/kratos:v0.9.0-alpha.2
    environment:
      - DSN=postgres://kratos:secret@kratos-postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - dcd-net
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.9.0-alpha.2
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://localhost
    ports:
      - '4455:3000'
    restart: on-failure
    networks:
      - dcd-net
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.9.0-alpha.2
    ports:
      # - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:secret@kratos-postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - dcd-net
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - dcd-net
  kratos-postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - dcd-net

  envoy:
    image: envoyproxy/envoy-alpine:v1.19-latest
    container_name: envoy
    ports:
      - 80:80
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - dcd-net

  profile:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: profile
    volumes:
      - ./src:/usr/app/src
      - ./e2e:/usr/app/e2e
      - ./angular.json:/usr/app/angular.json
      - ./tsconfig.json:/usr/app/tsconfig.json    
    networks:
      - dcd-net

networks:
  dcd-net:
    external: true