version: '3'

services:

  profile-api:
    build:
      context: ./profile-api
      args:
        START_COMMAND: $PROFILE_API_START_COMMAND
    container_name: profile-api
    environment: 
      - HOST_DATA_FOLDER=$HOST_DATA_FOLDER
      
      - NODE_ENV=$NODE_ENV
      - PROFILE_ADMIN_EMAIL=$PROFILE_ADMIN_EMAIL
      - PROFILE_ADMIN_PASSWORD=$PROFILE_ADMIN_PASSWORD
      - CRYPTO_ALGO=$CRYPTO_ALGO
      - CRYPTO_KEY=$CRYPTO_KEY
      
      - HTTP_HOST=$HTTP_HOST
      - HTTP_PORT=$HTTP_PORT
      - HTTP_SECURED=$HTTP_SECURED
      - HTTP_BASE_URL=$HTTP_BASE_URL
      
      - PROFILE_POSTGRES_HOST=$PROFILE_POSTGRES_HOST
      - PROFILE_POSTGRES_USER=$PROFILE_POSTGRES_USER
      - PROFILE_POSTGRES_PASSWORD=$PROFILE_POSTGRES_PASSWORD
      - PROFILE_POSTGRES_PORT=$PROFILE_POSTGRES_PORT
      - PROFILE_POSTGRES_DB=$PROFILE_POSTGRES_DB
      - PROFILE_POSTGRES_LOGGING=$PROFILE_POSTGRES_LOGGING

      - OAUTH2_INTROSPECT_URL=$OAUTH2_INTROSPECT_URL
      - OAUTH2_TOKEN_URL=$OAUTH2_TOKEN_URL
      - OAUTH2_REVOKE_URL=$OAUTH2_REVOKE_URL
      - OAUTH2_AUTH_URL=$OAUTH2_AUTH_URL
      - OAUTH2_PROFILE_URL=$OAUTH2_PROFILE_URL
      - OAUTH2_CLIENT_ID=$OAUTH2_CLIENT_ID
      - OAUTH2_CLIENT_SECRET=$OAUTH2_CLIENT_SECRET
      - OAUTH2_SCOPE=$OAUTH2_SCOPE

      - OAUTH2_HYDRA_ADMIN_URL=$OAUTH2_HYDRA_ADMIN_URL
      - OAUTH2_FIRST_PARTY_APPS=$OAUTH2_FIRST_PARTY_APPS

      - ACP_URL=$ACP_URL
    restart: on-failure

  profile-ui:
    build:
      context: ./profile-ui
      args:
        - BASE_HREF=$PROFILE_UI_BASE_HREF
        - DEPLOY_URL=$PROFILE_UI_DEPLOY_URL
        - CONFIGURATION=$PROFILE_UI_CONFIGURATION
    container_name: profile-ui
    environment:
     - NGINX_HOST=dwd.tudelft.nl
     - NGINX_PORT=8081
    restart: on-failure

  profile-postgres:
    image: postgres:9.6
    container_name: profile-postgres
    environment:
      - POSTGRES_USER=$PROFILE_POSTGRES_USER
      - POSTGRES_PASSWORD=$PROFILE_POSTGRES_PASSWORD
      - POSTGRES_PORT=$PROFILE_POSTGRES_PORT
      - POSTGRES_DB=$PROFILE_POSTGRES_DB
    volumes:
      - $HOST_DATA_FOLDER/profile/profile-postgres:/var/lib/postgresql/data
    # ports:
    #   - $PROFILE_POSTGRES_PORT:$PROFILE_POSTGRES_PORT
    restart: on-failure

networks: 
    default:
        external:
          name: dcd-net