version: '3'

services:

  profile-data:
    image: postgres:9.6
    container_name: profile-data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - $HOST_DATA_FOLDER/postgresql:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT

# networks: 
#     default:
#         external:
#           name: dcd-net