version: v0.7.1-alpha.1

dsn: postgres

serve:
  public:
    base_url: http://localhost
    cors:
      enabled: true
      allowed_origins:
        - http://localhost
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://localhost/profile
  allowed_return_urls:
    - http://localhost

  methods:
    password:
      enabled: true
    oidc:
      enabled: true

  flows:
    error:
      ui_url: http://localhost/profile/error

    settings:
      ui_url: http://localhost/profile/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://localhost/profile/recovery

    verification:
      enabled: true
      ui_url: http://localhost/profile/verification
      after:
        default_browser_return_url: http://localhost/profile

    logout:
      after:
        default_browser_return_url: http://localhost/profile/login

    login:
      ui_url: http://localhost/profile/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost/profile/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: dcd_v0
  schemas:
    - id: dcd_v0
      url: file:///etc/config/kratos/identity.schema.v0.json

courier:
  smtp:
    connection_uri: smtp://dutmail.tudelft.nl:25
    from_address: j.bourgeois@tudelft.nl
  template_override_path: /etc/config/kratos/templates/courier-templates
  templates:
    # we can specify here
    verification:
      valid:
        email:
          body:
            # plaintext and html are required when overriding the body
            html: file:///etc/config/kratos/templates/courrier-templates/verification/valid/email.body.gotmpl
            plaintext: file:///etc/config/kratos/templates/courrier-templates/verification/valid/email.body.plaintext.gotmpl
          # optional
          subject: file:///etc/config/kratos/templates/courrier-templates/verification/valid/email.subject.gotmpl
      # we can also omit the `invalid` field here if you wish to use the default built-in templates
      # or template_override_path
      # invalid:
        # same configuration structure as valid
    # this is also optional and can be omitted in preference for the default built-in templates
    # or template_override_path
    recovery:
      valid:
        email:
          body:
            # plaintext and html are required when overriding the body
            html: file:///etc/config/kratos/templates/courrier-templates/recovery/valid/email.body.gotmpl
            plaintext: file:///etc/config/kratos/templates/courrier-templates/recovery/valid/email.body.plaintext.gotmpl
          # optional
          subject: file:///etc/config/kratos/templates/courrier-templates/recovery/valid/email.subject.gotmpl
