serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://localhost
  consent: http://localhost/profile/consent
  login: http://localhost/profile/signin
  logout: http://localhost/profile/signout

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis